name: Checks

on:
  workflow_call:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Zig
        run: |
          curl -sL "https://ziglang.org/download/0.15.2/zig-x86_64-linux-0.15.2.tar.xz" | tar -xJ
          echo "$PWD/zig-x86_64-linux-0.15.2" >> "$GITHUB_PATH"

      - name: Format check
        continue-on-error: true
        run: zig fmt --check src/ cli/ tools/

      - name: Build
        run: zig build --summary all

      - name: Test
        run: zig build test --summary all
