name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  checks:
    uses: ./.github/workflows/checks.yaml

  security-audit:
    uses: ./.github/workflows/security-audit.yaml 
